services:
  postgres:
    image: postgres:18
    container_name: reorderly-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reorderly
    ports:
      - "3310:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
